server:
  port: 3009

spring:
  datasource:
    url: "jdbc:mysql://localhost:3308/shopflow_product"
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
      format-sql: true
    show-sql: true
  servlet:
    multipart:
      max-file-size: 500KB
      max-request-size: 500KB