server:
  port: 3011

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ming18380@gmail.com
    password: "gyon fyxx owqv xbsr"
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
  kafka:
    bootstrap-servers: localhost:9193
    admin:
      properties:
        request.timeout.ms: 300000
        default.api.timeout.ms: 300000
    producer:
      retries: 0
      batch-size: 16384
      buffer-memory: 33554432
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: myGroup
      auto-offset-reset: earliest
      enable-auto-commit: false
      auto-commit-interval: 100
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

    listener:
      missing-topics-fatal: false
      ack-mode: manual_immediate

