server:
  port: 8888
spring:
  cloud:
    config:
      server:
        native:
          search-locations: file:C:/Users/ADMIN/Desktop/springboot/ShopFlowBasic/config-server/src/main/resources

logging:
  level:
    org:
      springframework:
        cloud: DEBUG